### ISSUE TITLE
[Redesign] fetch stack with "filter" tags 

### ISSUE THREAD

**Issue by mydu** [medialab/hyphe-browser#102]
implement with api
- [x] filter webentities with no tag option: `get_webentities_mistagged`: `missing_a_category: false`, `multiple_values: false`
- [x] filter webentities with incomplete tag option: `get_webentities_mistagged`: `missing_a_category: true`, `multiple_values: false`

**Comment by boogheta** [comment]
@robindemourat It seems to me like the functionalities are there, remains the question of the design, maybe this part should be rediscussed tomorrow
