### ISSUE TITLE
Re-enable text related keyboard shortcuts in inputs

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#105]
Currently it is not possible to use `cmdOrCtrl + a`, `cmdOrCtrl + c`, `cmdOrCtrl + v` ... in inputs, as this feature is not provided by default by electron. It would be very useful globally, and especially for the URL bar (e.g. copy-pasting a URL).

**Comment by boogheta** [comment]
Ça fonctionnait dans l'ancienne version, donc il semble que ça ait disparu quelque part en route

**Comment by robindemourat** [comment]
relates to #71

**Comment by boogheta** [comment]
I believe this is a mac issue : on linux on both old and new versions, i can correctly paste urls using Ctrl+v.
So I figure this is precisely Cmd+ which does not work. Although I think it used to, @robindemourat or @arnaudmollo could you try on your mac for instance with these builds :
- https://github.com/medialab/hyphe-browser/releases/download/v1.0.1/HyBro-MacOSX.zip
- https://github.com/medialab/hyphe-browser/releases/download/v1.0/HyBro-Linux-64bit.zip

**Comment by robindemourat** [comment]
Just tested -> keyboard shortcuts work with this version.

**Comment by robindemourat** [comment]
I see that part of the code has been deleted in the new version : https://github.com/medialab/hyphe-browser/blob/v1.0.1/main.js#L104

Probably just re-adding corresponding menu items might solve this.

**Comment by boogheta** [comment]
It should indeed according to the comment line 109, well caught

**Comment by arnaudmolo** [comment]
Fixed by https://github.com/medialab/hyphe-browser/commit/e410684652e3a49e12467bf340cb18ae1f0f7f24 could you check on a non-mac keyboard @boogheta ?

**Comment by boogheta** [comment]
I confirm I can still paste into inputs, if you can too, let's close this one!
