### ISSUE TITLE
Update or delete react dev tools

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#106]
On some machines HyBro won't start in dev mode because of obsolete devtools incompatible with React 16+, disabling it within main.js fixes this issue, and I understand on machines where it starts they do not work anyways, so I guess we should either remove them completely, or find a recent version which would be compatible instead

**Comment by boogheta** [comment]
closed by https://github.com/medialab/hyphe-browser/commit/f7a2784b2b63cd76fa1308828e5631a0edaf6b02 ? cc @arnaudmolo

**Comment by arnaudmolo** [comment]
@boogheta It should be, but we have to test on your device

**Comment by boogheta** [comment]
Just did, it works well!
