### ISSUE TITLE
CSS fine adjustments 

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#113]
- [x] Styling of the browser url bar for new tabs is different from other tabs
- [x] + button for new tabs should not be in reverse italic
- [x] sidebar's scrollbars are too thin to be grabbed (both the global one and the cartel lists ones)
- [x] for the scrollbars, I think it should also apply to the one of the whole sidebar (when all cartels are opened in the Browsed webentity one
- [x] link to the homepage on the entity's name could be a cursor pointer ? (when we're not already on the homepage, or better disable the link in such case)
- [x] the link to the homepage on the WE's title should be disabled when the tab is actually on the homepage already
- [x] when next/previous buttons are disabled make them way more transparent
- [x] radio button for password to change to checkbox ?
- [x] The Filter button should propose a third option "no filter" to let one disable a filter without having to "reclick" it
- [x] On big screens, the sidebar being a bit large makes things a bit weird for the status change buttons being too distant
- [x] the list of corpuses of a server should not be horizontally scrollable
- [x] the list of webentities of a stack should not be horizontally scrollable
- [x] when hovering a button in the list of webentities and scrolling at the same time, the button moves!
- [x] Under Linux, the urlbar for new tabs is still slightly smaller in height than for the other tabs
- [x] Under Linux, the texts are not always properly centered (text is slightly shifted to the top in the urlbar, and text is slightly shifted to the right in fast action buttons)
- [x] homogenize buttons hover behavior: background change or not ? => #162
- [x] add check mark on selected language in application menu
- [x] counter of stacks: use scale instead of font size
- [x] in webentities lists, webentities with long names get on top of the action buttons, should we move the buttons ? cut the text ?

**Comment by boogheta** [comment]
I reopen for three small adjustments, we can discuss them:
- [ ] for the scrollbars, I think it should also apply to the one of the whole sidebar (when all cartels are opened in the Browsed webentity one
- [ ] the urlbar for new tabs is still slightly smaller in height than for the other tabs
- [ ] the link to the homepage on the WE's title should be disabled when the tab is actually on the homepage already

Also while testing this I encountered a weird bug where the whole tabs bar disappeared, but I can't reproduce it...

**Comment by robindemourat** [comment]
Thanks for the sharp eye !

> the urlbar for new tabs is still slightly smaller in height than for the other tabs

I could not reproduce this, we will have to check on your machine.

I propose to keep this issue open and add new small UI-related issues here.

**Comment by boogheta** [comment]
Yep perfect, I updated the list at the top with those from my above comment and those we discussed
