### ISSUE TITLE
Extra fixes and ideas to refine

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#117]
- [x] go trough all texts and translate to french (including the markdown for new tab)

- [x] activate pagination for all stacks, and reduce page size, 20? 50?

- [x] after multiple action in stack with pagination, it should reload all pages up to the current one

- [x] reset filter choice when changing status stack

- [x] disable download list of csv when no element in list (from filtering for instance), and display a "no result message"

- [x] fix csv version of downloadable tags

- [x] change text of "new entities found" since sometimes it can be entites removes => updted ?

- [x] in the branch multiple stacks : the next/previous entity buttons should be related the order of the current entity in the stack of its original status when

- [x] autoclick on scroll the load more?

- [x] in known webpages : for short urls remove leading slash / and use browser's history (localstorage) to display visited pages

- [x] (discuss) improve rendering of next/previous arrows when disabled (remove them ? at least no hovering), for instance when IN list has only one entity

- <s>[] disable Download menu in Server connexion (electron only allow to disable submenu, not main menu)</s> (partial fix by hiding the submenus, electron does not let one control main menus dynamically)

- <s>[] in INmodal's list of known pages, hovering urls should display a tooltip (the current tooltip is unstyled because the virtual list not allow to wrapper with `Tooltip`)</s> (duplicate in #166 )

- <s>[ ] (discuss) update the global status from the local actions (to handle time delay between "found new entities" and global status update)</s> -> #187

**Comment by boogheta** [comment]
More:

- que faire des onglets ouverts sur une entité en dehors de la lsite en cours (garder ou pas boutons next/previous / avoir une liste dédiée par onglet)

- gérer pour ou suis-je et pour tout rafraichissement de la liste les cas ou la webentité en cours n'est pas dans la liste, auquel cas on l'insère en haut de liste

- remetre degree webentité dans sidebar 

- redesign search/filter actions

- bug with tab bars disappearing

**Comment by robindemourat** [comment]
Moar:

- [ ] wording in in-modal : should we use "homepage" instead of "page d'accueil" to be consistent ?
- [ ] in-modal : when setting we name, allowing hitting enter for validation (in addition to clicking on "confirm"

**Comment by mydu** [comment]
- disable Download menu in Server connexion - cannot diable top-level menu item  https://github.com/electron/electron/issues/8703

**Comment by mydu** [comment]
## current stack search/filter on tags/pagination behaviour

related #119

### pagination
- reserve [viewed pagination number of each stack](https://github.com/medialab/hyphe-browser/blob/65e76539d0bf546d17af74a15619fd21e2b8caf9/app/containers/StackListContainer/StackListContainer.js#L105) to local state and auto-pagination if re-fetch stack is triggered(e.g. actions applied, switch between different stacks)
### search
- if input `searchString`, call `search_webentities` and set `searchedResult` with its pagination in local state
- disable api search but with local search if filter on tags is set 
### filter on tags
- re-fetch stack if filter on tags with `get_webentities_mistagged`, clear filter if change to another stack
- set pagination only if `stack==='DISCOVERED'`
