### ISSUE TITLE
Redesign inquiry overview header issue

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#118]
Right now filter seems to be a validate button - to redesign

**Comment by robindemourat** [comment]
I redesigned this to separate more filtering-related stuff and "load more", and search input and filters. Feedbacks welcome !

**Comment by boogheta** [comment]
looks good to me, shall we close ?

**Comment by robindemourat** [comment]
Still have to add a "show all" option to the filters list to be more explicit - i'll do that and then close
