### ISSUE TITLE
Improve search filter behavior in inquiry overview

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#119]
# The design problem

Right now the search feature only filters locally matching entity cards. This means researchers have to click on "load more" many times as long as the button displays to be sure they are reviewing all the search matching webentities.

In the same time, for matters of orientation, we don't want the use of the search feature to "mess up" with the list of entities as it was before the search. When clearing the search input it should be restored as it was beforehand.

# The technical problems

There is no available API endpoint for combining a search query and a filter on the status of tags.

# The new behavior

* 1/ when search input is changed, instantaneously update local list with a `filter` (current behavior)
* 2/ at the same time, in a debounce query the server for matching terms of at least two characters (display a loading state to client) -  using store.search_webentities with input keywords in allFieldsKeywords, and status of the current list as fieldKeywords (ask @boogheta for help :) )
* store matching terms in a separate array - in the UI append matching terms to local filtered list - with a pagination
* when search input is cleared, remove matching terms coming only from server and restore the main list as it was before

**Comment by boogheta** [comment]
It seems to fulfill the objectives, although some bugs remain which I've added to the list in #117
