### ISSUE TITLE
Redesign redirect+merge modal

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#124]
To display when in webentity A the page automatically redirects one to another page that belongs another webentity B

- [x] adopt new modal UI for the merge modal
- [x] Display a redirection modal that shows both urls and webentities names
- [x] Ask whether to follow the redirection or not
- [x] If not: remain on the page not redirected (display instead a special page saying : "we cannot display this page, it wants to be redirected to other url") and let user work on the A entity metadata
- [x] If yes: we display in the modal two more options 
  1. do not merge and put A in the OUT list, and redirect to B (in entity card of stack list indicate the change of status)
  1. merge webentity A within the target webentity B (in entity card of stack list indicate the merge)
  1. let user to choose the prefix of webentity B to merge to webentity A
- [x] set the modal's height to maximal possible height when using option 2 + 3
- [x] in the modal underline webpages urls instead of the blue highlighting
- [x] internationalize all redirection texts (modal, special page, ...)
- [x] trigger redirection modal also from a webentity which does not exist yet in the corpus: for instance cevipof.fr is not in the corpus but we type www.cevipof.fr in the urlbar
- [x] try to trigger it also whenever the url of a tab changes automatically (for instance here https://controverses.sciences-po.fr/sdfsdfsdfs )
- [x] check other cases cf #22

(this should handle #156)

Example https://t.co/D0tCHYSP6X => https://bit.ly/3fbwWld => http://www.cevipof.fr => http://ww.sciencespo.fr/cevipof/

**Comment by mydu** [comment]
cases that might need some more design:

  * do not merge and put A in the OUT list (then inside the stack list, A should disappear except it this is the OUT list, and B should also move to A's place, or right after)
  * or cancel to remain on A without redirection

the webentity is kept not to merge, would be an invalid webview (or some overlay on top), and some actions on side panel (for example -> set to 'IN') should be be disabled. need design some reminder to show why this is a invalid webentity

**Comment by boogheta** [comment]
Yes indeed, thx @mydu, cc @robindemourat

**Comment by boogheta** [comment]
- [ ] maybe try to trigger it also whenever the url of a tab changes automatically (for instance here https://controverses.sciencespo.fr/sdfsdfsdfs )

**Comment by boogheta** [comment]
I did a few tests and it seems good to me
I added three more boxes to check in the list, and it made me realise we should fix another bug added in #161

**Comment by mydu** [comment]
waiting for french translation in 
https://github.com/medialab/hyphe-browser/blob/d2e7b247b66f92a4ce444a81a576675853bbd0e6/app/translations/fr.json#L430-L443
