### ISSUE TITLE
The modal's list of known pages has duplicates

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#136]
The first url (the current one) can appear twice in the list of pages if it is already known, it should be deduped on the fly

**Comment by boogheta** [comment]
depends on #140

**Comment by arnaudmolo** [comment]
Fixed in 51d35101cd852b4805003b6298ab01c283c10715

**Comment by boogheta** [comment]
There are still problems when the current url has a trailing slash

**Comment by boogheta** [comment]
warning this might ressurect #134

**Comment by boogheta** [comment]
Last point to handle : 
remove trailing slash after tld for urls of proposed homepage coming from current prefix/page
