### ISSUE TITLE
Do not add a trailing slash at the end of urls in the urlbar

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#138]
For instance I have a webentity created for the prefix https://www.sciencespo.fr/cevipof/
When I click on it, it sends me to this page, but displays it with two slashes at the end

**Comment by boogheta** [comment]
it's due to prefixes with the trailing slash, so  it will be fixed when #134 is closes

**Comment by arnaudmolo** [comment]
yup, fixed in https://github.com/medialab/hyphe-browser/commit/51d35101cd852b4805003b6298ab01c283c10715

**Comment by boogheta** [comment]
fixed, but might also ressurect #136
