### ISSUE TITLE
Lost index of the webentity if url 'redirect' to another webentity which is not yet loaded into stack

### ISSUE THREAD

**Issue by mydu** [medialab/hyphe-browser#156]
Select a webentity from stack and if the **url redirect** (most use cases might be linkedin redirection) to another webentity, the id of the webentity will be updated, but this id is not found yet in the current stack because the stack only loaded partially, so prev/next arrow is untraceable from index of the original webentity. then it will always lead to the first item of the stack.
Even we fully loaded the stack, the updated id is not next to the original id, which is also a bit lost

**Comment by boogheta** [comment]
Good catch
I guess maybe we could keep in each tab a reference to the latest actually existing index within the list?

**Comment by boogheta** [comment]
This raises also the question of reintroducing the mechanism of triggering automatically a merge modal whenever we're redirected to properly handle the intended webentity cf #124
