### ISSUE TITLE
Add indicator of changing status/merge to another entity on EntityCard in StackList

### ISSUE THREAD

**Issue by mydu** [medialab/hyphe-browser#158]
Add an indicator on EntityCard after changing its status or merge to another entity(in stack list)before actualize the stack list, to better handle the case for #124 @robindemourat

**Comment by robindemourat** [comment]
@mydu I made a design proposal for this in the `new-mockups` branch (in `EntityCard` story of the storybook). At your disposal to precise/discuss it !

**Comment by mydu** [comment]
thx @robindemourat !, works on my side, I wait verification from Benjamin
