### ISSUE TITLE
Update webentity's referrers/referrals/paginate_pages when crawling is finished

### ISSUE THREAD

**Issue by mydu** [medialab/hyphe-browser#165]
1. set uncrawled webentity to "IN" and start crawling, currently there is no response when it finished until manually call `declare_page` to get the `crawling_status` of the webentity
2. change prefix of an exist crawled webentity and re-crawl it, same issue that no way to know when it will finish

need to add `listjobs` api call in `CorpusStatusWatcher` to get this information

**Comment by boogheta** [comment]
All right let's reopen Milestone V and include this one within since adding the number of linked entities revealed this as a visible bug.

I think the problem is larger than just depending on whether the entity was finishd crawling, since other crawls could also reveal more citing entities without any way to know how much.

But I still don't think we should refresh all refferers automatically many times since the operation is costful.

So... here is an alternative proposal: let's do like with the stacks and add within the list of linked entities displayed at the top a button to refresh the list exactly the same way as in the stacks. It should be triggered whenever the number of entities in the displayed list is different than the value stored in the entity (indegree or outdegree). And I guess this means we should also always display in the title the indegree/outdegree value like originally.

**Comment by boogheta** [comment]
All right that's a start, but I see a few things to fix:
- [ ] the content of the cartel takes some time to update and therefore displays weird things when switching from Citing to Cited. For instance, on the dev instance and corpus "test redir", go to https://abes.fr/ then open Linked entities and switch between the two. Maybe remove the content of the list and display a loader before displaying the actual content whenever switching between Cited/Citing ?

- [ ] I see here <https://github.com/medialab/hyphe-browser/commit/ba1ae36d1eec26d2ffdfe62a91ef4df80d94d9b9#diff-5dfeff53e62a1cd123568b64c09dce846ec96358554894decff10c23dae12aa8L444-L450> you removed all existing extra calls to fetch referrers/refferals after linkedentities actions. It is definitely a gain for when we're only changing the status of some entities, but in the case of merge actions, this is the one case where we know for sure we should refresh without asking the user to do so, so I would reinclude these fetchReferrers/als calls always when validating the MergeActions Modal

- [ ] Not sure this code line will remain after fixing the previous point, but the line here <https://github.com/medialab/hyphe-browser/commit/ba1ae36d1eec26d2ffdfe62a91ef4df80d94d9b9#r44962127> should definitely be fixed

- [ ] some styling adjustment which I proposed in #193

**Comment by mydu** [comment]
@boogheta about removing `fetchReferrals/fetchReferrers` calls at https://github.com/medialab/hyphe-browser/commit/ba1ae36d1eec26d2ffdfe62a91ef4df80d94d9b9#diff-5dfeff53e62a1cd123568b64c09dce846ec96358554894decff10c23dae12aa8L444-L448, if we re-fetch them every time when doing merge entity, there is no need to add actualize button on it, right? it will update the list immediately and the indegree/outdegree number get from declarePage should be the same as referrals/referrers counts.

**Comment by boogheta** [comment]
Yep, for these cases it won't be necessary: after doing merge actions we now for sure it should be reloaded and values we get from degrees and number of linkedentities should indeed be the same most of the time then yes.
But the idea of the actualize button is to handle more cases globally, such as new entities coming from crawls etc
If it's conditionned to in/outdegree being different from entities count, then I guess these are two separate things and you should not handle it differently

**Comment by mydu** [comment]
sure, I will add them back for merge cases.
But actually for new entities crawled cases, currently hybro could still not detect if crawling is finished or not until manually call `declarePage` (which means user need to revisit the page) if we are not adding `listjobs` on top of the app. If user start a crawl and stay at this page, none of those `knownpages/referrals/referrers` list will update automatically :(
so do you want to add `listjobs` api call in `CorpusStatusWatcher` or we add an extra indicator to ask user manually `declarePage` somewhere?

**Comment by boogheta** [comment]
I think it's too costly for a limited interest: people are supposed to browse so they will get updates whenever changing page which I think is sufficient. Also monitoring when the current entity's crawl is finished does not necessarily inform about all changes, for instance you might want to refresh also when another entity was crawled returning links to the current one, but there is no way to know that. So I feel like adding this opens a window that will be hard to reclose ;)
Actually if we really want to handle this, I would rather do something simplier than relying on listjobs: rerun declare_page on the current tab every minutes or so. This way if linkedentities or knownpages should be refreshed the user will know it eventually.
I'll open two more issues regarding this, so this one remains limited to the updates for linkedentities

**Comment by boogheta** [comment]
The first problem is fixed, but with entities linked to many other there still remains a short weird behavior: it first displays the actualize button and None while it's loading/processing the list and then removes the actualize to display the list.
Could we instead : 
- [ ] if it's currently loading the list of pages, not display the actualize button
- [ ] if the in/outdegree is not zero and we are loading, not display None but some loader instead?

**Comment by boogheta** [comment]
There's no loader but it seems acceptable like that to me
