### ISSUE TITLE
electron migration issues

### ISSUE THREAD

**Issue by mydu** [medialab/hyphe-browser#171]
at branch https://github.com/medialab/hyphe-browser/tree/electron-upgrade
- [x]  [`context-menu`](https://www.electronjs.org/docs/api/web-contents?q=webviewtag#event-context-menu) event of the webContents attached with `<webview>` not work properly and DOM `contextmenu` event is not triggered anymore
- [x] `webRequest.onBeforeRediret` event called multiple times for single redirect 
- [x] dns error redirect could not  be handled anymore
- [x] lint rules: react no-deprecated - refactoring `componentWillReceiveProps`

**Comment by boogheta** [comment]
@mydu I did not encounter any crash or behavior change between the two branches in-modal & electron, so I think we can go ahead and merge electron branch in in-modal.
Then I still need to do some curation of the issues and identify the required ones before we publish the next release, but we shall soon merge everything to master I believe! \o/
