### ISSUE TITLE
Warning: Unknown props `useragent`, `autosize` on <webview> tag

### ISSUE THREAD

**Issue by Delapouite** [medialab/hyphe-browser#18]
https://github.com/facebook/react/issues/7357

**Comment by Delapouite** [comment]
https://github.com/electron/electron/issues/6046

**Comment by boogheta** [comment]
Hey @Delapouite, where these pointed just out of a reminder to yourself? It seems to me like WebView's useragent is properly set at least.
Regadring autosize, I noticed that when opening a tab, especially the Special Hyphe one, it initially is a small rectangle before reachign its actual correct size, not sure how to handle this, maybe it is linked to the autosize issue you pointed?

**Comment by Delapouite** [comment]
Yes those 2 links are mainly here as a reminder of wha'ts going on with the warning messages logged each time.
I don't think there's a direct consequence on the weird resizing behavior though.
