### ISSUE TITLE
Redesign filter button in Inquiry Overview

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#186]
- [x] make the filter button larger and display within a shorter version of the current choice ("all webentities" / "only untagged webentities" / "incompletely tagged webentities")
- [x] the current behavior unselects a preselected option if one selects it again, it should rather remain selected in such case : clicking an option always selects it

**Comment by boogheta** [comment]
(from @mydu's https://github.com/medialab/hyphe-browser/issues/117#issuecomment-679030112)

## current stack search/filter on tags/pagination behaviour

related #119

### pagination
- reserve [viewed pagination number of each stack](https://github.com/medialab/hyphe-browser/blob/65e76539d0bf546d17af74a15619fd21e2b8caf9/app/containers/StackListContainer/StackListContainer.js#L105) to local state and auto-pagination if re-fetch stack is triggered(e.g. actions applied, switch between different stacks)
### search
- if input `searchString`, call `search_webentities` and set `searchedResult` with its pagination in local state
- disable api search but with local search if filter on tags is set 
### filter on tags
- re-fetch stack if filter on tags with `get_webentities_mistagged`, clear filter if change to another stack
- set pagination only if `stack==='DISCOVERED'`

**Comment by mydu** [comment]
text inside filter button:
https://github.com/medialab/hyphe-browser/blob/bcd5be4548421d00ab7c3f25fbe43ecc095e8c3a/app/translations/en.json#L219-L221

https://github.com/medialab/hyphe-browser/blob/bcd5be4548421d00ab7c3f25fbe43ecc095e8c3a/app/translations/fr.json#L171-L173
