### ISSUE TITLE
Hyphe-Tab malfunctioning after creating a new corpus

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#19]
When creating a new corpus, the hyphe tab doesn't work at first in some cases (to be identified) and only works after having closed and reopened the corpus (or even the browser?)

**Comment by boogheta** [comment]
@thomastari might have more experience and insights to share on this specific issue

**Comment by boogheta** [comment]
@thomastari and @audreybaneyx might have more experience and insights to share on this specific issue

**Comment by thomastari** [comment]
nope it is systematic (every case of new corpus, you need to close it once before you can access H tab

**Comment by paulgirard** [comment]
I confirm I could create a corpus and hypeh tab was working.

A maybe related issue.
If I start an existing but stopped hyphe corpus from Hybro, the Hyphe tab is first set on the copora list of the server not on the corpus.
If I close the corpus and reopen the corpus once launched, the hyphe tab is correctly set on Hyphe network page.

**Comment by mydu** [comment]
related to #55
