### ISSUE TITLE
Keyboard shortcuts seems no more functional since electron8

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#190]
Ctrl + t 
Ctrl + w
Ctrl + tab
etc.

**Comment by boogheta** [comment]
:+1:

**Comment by boogheta** [comment]
Mmm actually not in fact: it seems like these globalShortcut are system wide, meaning when HyBro runs, all these shortcuts do not work anymore within any other software such as Firefox or Chrome which sounds a bit problematic :)

**Comment by boogheta** [comment]
@mydu all right back to the original issue, so to be precise, it seems like shortcuts work, except if one click within the webview, then until we click outside of it they don't work anymore

**Comment by mydu** [comment]
@boogheta  should works now, but we need to find a new shortcut for reload window(for development only), the default ones `'Ctrl+R', 'F5', 'Ctrl+Shift+R', 'Ctrl+F5', 'Shift+F5', 'Cmd+Shift+R', 'Cmd+F5'` are registered for reloading tab
Use **'Ctrl+L',** for now
https://github.com/medialab/hyphe-browser/blob/0d27fc7cddee57a4603fbe4b0ac43b357d00fd76/main.js#L153-L156

**Comment by boogheta** [comment]
Great!
For the dev reload, I propose shift+ctrl+l instead which is less at risk to be typed involuntarily

**Comment by boogheta** [comment]
Sorry I reopen as well : when pressing F12, we have a javascript error popup that raises
