### ISSUE TITLE
Improve design of validate actions buttons at the bottom of lists

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#193]
Two suggestions here:

- [x] in the LinkedEntities cartel, the cancel/apply action buttons are displayed without any top margin that would separate them from the actual list. In the Stacks it's not the case, there is a margin, it would be best to have it as well here

- [x] in both Stack and LinkedEntities, these extra buttons show up on top of the lists, making it shorter, while the "download csv" button remains accessible. I'm thinking that when one started to click fast actions, we could disable the possibility to download and actually display the cancel/apply button on the "Download CSV" button's place instead. This would save some space without really reducing functionalities I believe. What do you think @robindemourat and @mydu?

**Comment by mydu** [comment]
agree! looks less pack
