### ISSUE TITLE
Add actualize button within list of known webpages when necessary

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#194]
The same way it exists now within LinkedEntities (cf #165), we should allow to refresh known webpages when their number is diferent from webentity.total_pages

**Comment by boogheta** [comment]
Seems good, except for the wording that speaks about webentities instead of pages, I'm fixing this.

But like for the webentities, we might wanna trigger a declare_page as well after refreshing webpages since during crawls this result in the actualize button remaining there after clicking it.

**Comment by boogheta** [comment]
cf https://github.com/medialab/hyphe-browser/commit/70049136f4b95e39a42706c6acf4cc7f147e9381#r45028031
It seems like now it only refreshes when the number of pages collected and anounced is the same (so in the case when we actually don't need to refresh), I thunk this should be the opposite?

**Comment by mydu** [comment]
`fetchPaginatePages` is a repeat call until `pages_total === pages.length`, so we should not keep calling `declare_page` until it will finish ?
https://github.com/medialab/hyphe-browser/blob/70049136f4b95e39a42706c6acf4cc7f147e9381/app/actions/webentities.js#L219-L228

**Comment by boogheta** [comment]
Ha I understand, but yes you should rather stop the fetchPaginatePages based on when token becomes null, since the number of total_pages from the webentity can have changed in the mean time.
So that means two fixes:
- [ ] in fetchPaginatePages rely on token != null instead of webentity.pages_total
- [ ] after fetchPaginatePages call declare_page if pages_total !== pages.length, instead of the opposite

**Comment by mydu** [comment]
yes, and I had add `declare_page` when reload tab in https://github.com/medialab/hyphe-browser/commit/ddee45691081a2c331ad7c9acf863d79e145d518
