### ISSUE TITLE
Citing number is not equal to indegree if change entity status from IN to others

### ISSUE THREAD

**Issue by mydu** [medialab/hyphe-browser#197]
This is due to the fact Hyphe does not account into in/out-degrees links from entites being OUT or DISCOVERED.
I guess for HyBro's convenience, we should add within Hyphe different metrics like real-in/out-degrees that would account them
But in the mean time, we should rather:
- [ ] display the number of entities we display instead of the in/out-degrees within the linkedentities tab titles
- [ ] display the actualize button based on in/out-degree !== citing/cited_entities.filter(we => we.status === "IN" || we.status === "UNDECIDED").length

**Comment by mydu** [comment]
- [ ] display the undirected_degree -> ?
https://github.com/medialab/hyphe-browser/blob/e8ecd647e6bcdb89a641db0bbafe4d2125d6b3b9/app/containers/WebentityBrowseContainer/WebentityBrowseLayout.js#L265

**Comment by boogheta** [comment]
@mydu Regarding the undirected degree it is the one displayed in the title of the cartel already, where else did you wan to display it?

For the actualize check it might be more complex than what I wrote initially actually. Maybe we need to use filteredList only when working with referrers and not with referrals. I need more time to think about this better...

**Comment by mydu** [comment]
@boogheta temporary fix - show refresh button conditionally when
1. under referrers list - difference between `filteredList.length` and `indegree `
2. under referrals list - entity is set to IN and `carwling_status == 'RUNNING'`

but `undirected_degree` number is not handled conditionally yet, might hide it?

**Comment by boogheta** [comment]
OK now I understand better the issue.
I guess until we add into hyphe's API actual real degrees in the whole corpus, the choices you made make sense.
And I understand now the need to hide undirected degree as well indeed. I'm pushing it right now.

This also makes me realize we should probably order the webentities displayed in Linked Entities by Status (IN then UND then DISC then OUT) then by alphabetical Name. I'm pushing this as well now
