### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#200]
- [x] better distinguish warnings from errors and infos
- [x] make download alert a warning notification
- [x] make info/error notifications after completion batch actions / modal (MERGE ACTIONS MODAL, REDIRECTION MODAL, <s>BATCH ACTIONS</s>)
- [x] <s>handle API calls errors as notifications ?</s>

**Comment by boogheta** [comment]
@robindemourat We have three different types of notifications displaying in the topbar: info / warning / error, but currently we only use two colors : blue for info and red for warning and errors, what color choice would you make instead for warnings?

**Comment by robindemourat** [comment]
In order to follow the convention what would you say about a yellow (possibly the same as the one for the undecided list) ?

**Comment by boogheta** [comment]
sounds good to me, will try it (maybe in january though ;) )
