### ISSUE TITLE
Automatize builds on releases via GH Actions

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#207]
Like @Guillaume-Levrier does in Pandorae for instance https://github.com/Guillaume-Levrier/PANDORAE/blob/stable/.github/workflows/build.yml

**Comment by Guillaume-Levrier** [comment]
Well @Guillaume-Levrier is not really doing it yet, some additional electron-builder config is required.

**Comment by boogheta** [comment]
nearly there :)

**Comment by boogheta** [comment]
done in may 2023 https://github.com/medialab/hyphe-browser/commits/autobuild
