### ISSUE TITLE
edition of the name of the WE while defining a new WE

### ISSUE THREAD

**Issue by thomastari** [medialab/hyphe-browser#21]
the WE name field lights up when we are defining a new WE - misleading us into thinking we can change the name at the same time?

**Comment by boogheta** [comment]
it lights up because there are information that are updated in function of the selected prefix so I think the behavior should remain, but maybe we could make it less flashy, like more grey or such?

**Comment by thomastari** [comment]
yes, I understand it is tricky to edit the name at the same time you define a new WE because it is misleading - to make it greyer could be a good option
