### ISSUE TITLE
merging problems left

### ISSUE THREAD

**Issue by thomastari** [medialab/hyphe-browser#22]
some WE still appear in the prospection list although they are IN (cf 2 top WE in the prospection list of the students2017 / ID corpus) - no merging proposed.

**Comment by boogheta** [comment]
The fix never intended to fix them all, it's really really complex to do, this is only one of the numerous cases that will remain for a while unfortunately
- javascript redirections
- html meta redirection (`<HTML> <HEAD><META HTTP-EQUIV=Refresh CONTENT="0; url=http://www.discovery.org/multimedia/idtf/">  </HEAD> </HTML> `)

**Comment by boogheta** [comment]
I think all cases are now handled \o/ via @robindemourat & @mydu's work on #124's modal
I still see two potential border usecases to handle but will add a specific issue for it
