### ISSUE TITLE
end of the prospection list

### ISSUE THREAD

**Issue by thomastari** [medialab/hyphe-browser#26]
the prospection list is quite limited compared to the IN list?

**Comment by boogheta** [comment]
Not sure I understand the question: do you mean in size?

If so, the behavior is to load full lists for everything except for the prospection.
The size of the prospection batches is currently set to 200, which in my opinion is maybe actually a bit high already if we want to push the user to reload the propsect stack regularily and get it updated with recent changes

**Comment by thomastari** [comment]
you are right
