### ISSUE TITLE
Fix missing application icon on some OS

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/hyphe-browser#32]
The electron application does not always expose its icon, notably on Mac

Was:
Elle é où l'icone d'appli?

**Comment by Yomguithereal** [comment]
L'application n'a pas d'icone sur mac. Ou du moins cette icone ne s'affiche pas.

**Comment by Yomguithereal** [comment]
Je peux pas ya pas d’internet aux états unis.

**Comment by robindemourat** [comment]
Possibilité d'utiliser le package [`electron-icon-maker`](https://www.npmjs.com/package/electron-icon-maker) pour être sûr de couvrir tous les cas ([ex d'implémentation ici](https://github.com/peritext/ovide/blob/master/package.json#L33))
