### ISSUE TITLE
Add "export" buttons on context menus

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#36]
Each list of the sidebar's "Context" menu should be individually exportable with some button which clicked would download a CSV file containing all available meta on each element, and ideally named something like CORPUS-NAME_WEBENTITY-NAME-OR-ID_NAME-OF-THE-LIST.csv
Warning: electron might use a default download directory, ensure that the user is always asked where he wants to store the file

**Comment by mydu** [comment]
@boogheta the data element is a nested object, need to discuss the list of attributes people might interest to export

**Comment by boogheta** [comment]
I will be off the next two days, so I propose you start with everything available at the first level and list here the other, and we will adjust when I'll be back?

**Comment by boogheta** [comment]
It would be good if we could force electron to display a popup asking where the user wants to download the file, on my machine it just saves it without telling me where :)

**Comment by boogheta** [comment]
I added flattening the tags object the same way it is done in Hyphe's front and changed the names of the exported files. Another thing that should probably be done before closing this would be to replicate the format of Hyphe's front exports for the webentities exports (especially column names, cf https://github.com/medialab/hyphe/blob/master/hyphe_frontend/app/views/export.js#L14-L131 )

**Comment by boogheta** [comment]
The breaks on entities without tags
