### ISSUE TITLE
Add export options related to the whole corpus 

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#43]
Add an application menu named "Download" (Télécharger in french) with the following entries : 
- [x] IN WebEntities as CSV
- [x] IN WebEntities as JSON
- [ ] IN WebEntities as Sitography
- [x] IN + UNDECIDED WebEntities as CSV
- [x] IN + UNDECIDED WebEntities as JSON
- [ ] IN + UNDECIDED WebEntities as Sitography
- [x] line separator
- [x] Tags as CSV
- [x] Tags as JSON

Entities and tags data should come from querying the API
Tags should include the number of occurences of each tag within the corpus (available in the route store.get_tags)

CSV and JSON formats should respect Hyphe's frontend current export features
Sitography format should be finely described by @thomastari here, but until then, let's says something like a list in markdown format with the Name and Homepage of an entity on each line, ordered alphabetically by names?

**Comment by mydu** [comment]
Not implement the functionality yet, the menu bar now looks like

### Language menu
![image](https://user-images.githubusercontent.com/3991275/56816680-5682fa80-6844-11e9-9ca4-216ecde1d3b3.png)

### Download menu
![image](https://user-images.githubusercontent.com/3991275/56816769-7f0af480-6844-11e9-8bee-afcecf808a37.png)

**Comment by boogheta** [comment]
cc @thomastari

**Comment by boogheta** [comment]
We need more options, such as ordering of webentities, so a modal would probably be more fitted than a set of lines in the menu
To be thought and designed first

**Comment by boogheta** [comment]
I'll close this one which is now handled and open a new one for the improvements considered
