### ISSUE TITLE
cited WE in context menu

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe-browser#47]
When working on a corpus we have to merge Web Entities which belongs to the same actor but using different domain like social networks.

To help users do this very common but time consuming task, it could be great to add a context menu which list the most cited WebEntites by the current one or silmply by the current page done live in hybro JS stack ?

To be discussed

**Comment by audreybaneyx** [comment]
good idea !

to go further, it would be a good idea to automatically choose/modify the start page of the Web entity under which we have gathered the others. We could exclude the URLS containing twitter, instagram or Facebook references and choose the most related URL (in and out) for the WE.

**Comment by boogheta** [comment]
@paulgirard I guess you're using an old version of HyBro, @mydu added changed parent/children entities into Cited/Citing entities in the context menu last year.
Although you're idea is interesting for the context of the single current page, this might be an idea to explore further (but would need to be precised and designed)

@audreybaneyx I don't really understand your point. I guess you're talking about homepage and not startpages (the starting points of the crawls) and about the merging issue? In which case I think it is more a Hyphe than HyBro issue and more fitted there https://github.com/medialab/hyphe/issues/291

**Comment by paulgirard** [comment]
Yes sorry about that cited entities are in teh context !
I close
