### ISSUE TITLE
add a 'merge' button in entities box in context menu ?

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe-browser#49]
In context menu there is cited entities and citing entities. 
Great.

It would be great to add a merge button into the entities boxes which could merge the entity which has the button into the entity being currently opened in the current tab.
Miight need a message to confirm everything went fine.

There might be issues related to this proposition usage and technical speaking.
So I leave it as a question.

**Comment by boogheta** [comment]
Good idea indeed, but I feel like this is borderline with the "too much complex features" limit intended for students, worth discussing with @thomastari . Although I feel like it could be very useful, In which case maybe make it visible only in some kind of advanced mode (activable form the application menu?)
Also if this exists, I feel it would be also useful with parent/children entities, which might be a reason to bring them back in extra Context tabs?

**Comment by paulgirard** [comment]
or a config somewhere

**Comment by thomastari** [comment]
i think it is quite useful and not "advanced" since it is an obvious and common sociological issue, when an actor communicate through several media and website or when we want to define a WE as a subcollection of pages from a website addressing diverse issues.

**Comment by boogheta** [comment]
great then! :) one more feature to add to @mydu's todo ;)

**Comment by audreybaneyx** [comment]
it's a great feature to add to hyphe browser. it's a bit complicated for students but it seems a logical methodological step to add to the tool since we - as "teachers" - have to explain what is a web entity and how to handle them.

**Comment by paulgirard** [comment]
Ok I can see the button on the 'entités citantes' (citing) but actually it's more needed in the "Entités cités" (cited) list.
Can you add it there to  so that I can test ?

**Comment by paulgirard** [comment]
Would be better to add the names of the tow web entities to be merge in the modal which ask for confirmation.

**Comment by mydu** [comment]
Message added, need to change the translation in `fr.json`

**Comment by paulgirard** [comment]
works great, very useful ! thank you @mydu !

Just one detail. We should reload the context list from which the merge button were hit to remove the web entity which has been merged.
Actually either reload the list or remove the merged one from the list ? 
Reload would be cleaner I guess ?

**Comment by boogheta** [comment]
As discussed it would probably be worth reloading also the current entity after a merge action, in order to reflect in the sidebar the modifications brought by the merge (mostly tag values)

**Comment by paulgirard** [comment]
looks good to me.

Maybe we should add a loader on the webentity panel when relaoding after a merge ?

**Comment by boogheta** [comment]
Yep I think it would be good to disable the sidebar with a loader and refresh the metadata of the current entity as well as its contextual list before
