### ISSUE TITLE
everlasting loading website

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe-browser#52]
Sometimes some website are loading for ever.
The Hyphe control panel does not load (waiting for the website to be loaded ?).
Therefore Hybro can't be used at all for those website whereas the web site can be read in Hybro.
It's just the loading phase which seems blocked.

Here is one example : www.lengadoc-info .com

Two workarounf everlatsing loading website : 
- doe not wait for the end of the laod to display the hyphe panel
- add an icon to stop the load if too long.

**Comment by paulgirard** [comment]
If I click on relaod icon : 
in BrowserTabContent.js?49e1:167
```
Object {errorCode: -3, errorDescription: "", validatedURL: "about:blank", pageURL: "https://lesmoutonsenrages.fr/"}
CustomError {name: "AbortedError", code: -3, type: "system", message: "An operation was aborted (due to user action)."}code: -3message: "An operation was aborted (due to user action)."name: "AbortedError"stack: (...)get stack: stack()set stack: stack()type: "system"__proto__: ChromiumNetError
```

But If I click multiple times, the hypeh panel finnaly appears even if the website is till loading (loader icon still spinning) ?

**Comment by boogheta** [comment]
At least it should not freeze the panel from being displayed and used, a spinner inside the context could also do, and ensuring to abort the running calls when refreshing or leaving the webentity would definitely help

**Comment by paulgirard** [comment]
This issue is blocking my usage of Hybro.
It should be place in high priority if someone can replicate this behaviour.

**Comment by mydu** [comment]
@paulgirard this might be due to the electron fail-load webview event, seems there is no setting to a timeout for this failure, I just enabled the display of panel anyway when you manually click the reload icon to terminate the everlasting loading. please test it on your corpus to see if it still freeze your Hybro?

**Comment by paulgirard** [comment]
with lengadoc : the website loads but the hyphe panel takes a long time (a few sec) before been displayed.
les moutons enragés works too.

Ok looks like a good fix for the main issue ! :+1: 

But we might ask for "entités citantes" "entités citées" "pages citées" data only if the user asks them to avoid the hyphe panel lag to be displayed (or not wait for the requests answers to display the panel ?)

**Comment by boogheta** [comment]
normally the context queries are not blocking the sidebar display, there is a loader inside, so I don't think the problem is there (but I'm not sure where else :p )
