### ISSUE TITLE
Create a corpus error message handler

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe-browser#54]
I created a corpus.
The server replies a 200 answer but with: 
```
{"fault": "Fault", "faultCode": 8002, "faultString": "[Errno 28] No space left on device"}
```

The UI doesn't not handle thie fault message correctly. It just hangs on the loading gif.
We should warn the user.

**Comment by boogheta** [comment]
This seems to do the trick for such cases, but behaves wrongly on another case of corpus creation error described below.
 
When trying to create a corpus with the same name as an existing one, the API returns a {code: 'fail', message:'Error, name already exists'}, but we raise a confusing error saying the server's resources are full. It should instead say so to let the user know he can go through by simply changing the selected name.
