### ISSUE TITLE
initialize src/url of the webview of hyphe-tab is incorrect when corpus is not ready

### ISSUE THREAD

**Issue by mydu** [medialab/hyphe-browser#55]
To reproduce:
1. select a corpus which status is not 'ready'
2. click on Hyphe tab

Behaviour:
redirect to hyphe login page for corresponding server

Investigation:
corpusWatcher will call fetchCorpus until its status is ready, no handling for the webview of hyphe tab

**Comment by mydu** [comment]
Note: this fix will only works if the corpus is ready
workaround: Hide hyphe-tab if corpus is not ready?

**Comment by boogheta** [comment]
I don't completely understand the point here : hyphe browser should rather remain on the server/corpus selection list until the corpus is ready : we shouldn't be able to use any browser tab until it's ready

**Comment by mydu** [comment]
do you mean this `status.corpus.ready` property?
https://github.com/medialab/hyphe-browser/blob/master/app/components/CorpusStatusWatcher.js#L46
the value is always `false` for first get_status

**Comment by boogheta** [comment]
Yes, when we open a corpus, the API gets à start_corpus (or create_corpus) query but there's a small gap before the corpus is actually ready, so the interface should display a loader and not open the browser part until the corpus is indeed ready

**Comment by mydu** [comment]
oh I did not see the loader, will find and enable it back
