### ISSUE TITLE
deleting a corpus : strange behaviour

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe-browser#56]
To reproduce: 
- create a corpus 'to be deleted'
- got o hyphe tab / settings /
- click "destroy corpus"
(- close the corpus, I am not sure if the UI change automatically to coprus list ?) 
- open an other corpus

Problem 1:  The title of the corpus was the old one 'to be deleted' in the title bar
Problem 2: Hybro was submtitting get_status requests every ~0.5s with this payload :
```
{"method":"get_status","params":["to-be-deleted"]}
```
which answers : 
```
[{"code": "success", "result": {"corpus": {"ready": false, "status": "stopped", "message": "Corpus is not started", "corpus_id": "to-be-deleted"}, "hyphe": {"crawls_running": 0, "crawls_pending": 0, "corpus_running": 1}}}]
```

**Comment by boogheta** [comment]
I think the problem is that using such features from Hyphe regular front were not intentionned to be used within HyBro and therefore not tested there.

A logical behaviour would be that destroying a corpus from the Hyphe tab within Hybro would close the corpus and go back to the corpus selection menu, but I don't think this is the case, leading to the described behavior

**Comment by mydu** [comment]
related https://github.com/medialab/hyphe/issues/302

**Comment by boogheta** [comment]
It still behaves weirdly when we try and do that.
In such case HyBro should understand the corpus does not exist anymore and close the corpus to go back to the corpus list for the current server

**Comment by boogheta** [comment]
it ccan probably be caught by the refresh status calls, which should return messages such as the corpus does not exist, in which case we should exit the corpus and go back to the corpus selection list

**Comment by arnaudmolo** [comment]
When a call to an unexisting corpus is done, the server answers by a "stopped" error message.

```
curl 'http://hyphe.medialab.sciences-po.fr/beta2-api/' -H 'Pragma: no-cache' -H 'Origin: null' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) hyphe-browser/0.1.0 Chrome/61.0.3163.100 Electron/2.0.18 Safari/537.36' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' --data-binary '{"method":"get_status","params":["random"]}' --compressed
```
respond with
```
[{"code": "success", "result": {"corpus": {"ready": false, "status": "stopped", "message": "Corpus is not started", "corpus_id": "zadza"}, "hyphe": {"crawls_running": 0, "crawls_pending": 0, "corpus_running": 0}}}]
```
