### ISSUE TITLE
Make annotations use more understandable

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#61]
Users get confused by the differents wordings and behaviors of annotations in HyBro which are a mix of notes and freetags ("Annotations" menu, "add a tag" placeholder, autocompletion, values displayed as tag boxes within a label with a cross).

So here's a set of modifications to better explicit these are intended for actual annotations:
- [ ] Reword the menu title : "Annotations" -> "Research notes" ("Notes de recherche" in fr) 
- [ ] Reword the placeholder : "Add a tag" -> "Add a note" ("Ajouter une note")
- [ ] Remove autocompletion
- [ ] Display values as separate notes, one by line, maybe with a specific "note" design
- [ ] Reword the "Categories" menu as "Tags"

Also, this raises the question of also keeping the possibility of having freetags as well, separated from these notes, effectively called Tags or Free Tags and keeping the same behavior as the current annotations. What do you think @thomastari @paulgirard @jacomyma ?

**Comment by jacomyma** [comment]
@boogheta  Could you precise something unclear: is this proposal to replace all tags by notes, or only free tags by notes?

**Comment by paulgirard** [comment]
I think it's only for free tags which were renamed annotations in Hybro.

Having research notes has described here is very necessary.
But as you mentionned  is that really a replacement of free tags ?  Do we want to remove free tags completely ? 

IMO we don't need free tags as we can create new tags category.
But I might miss a usage scenario.
The only feature that we would miss by dropping free tags is multiple choice tagging.

Note: whatever the decision it would require to do the same in Hyphe.

Note 2 : A rapid fix would be to simply remove the autocompletion on hybro annotations which is a pain.

**Comment by boogheta** [comment]
Yes I confirm, regular tags with categories remain no matter what! :)
The question only concerns freetags, which are currently called annotations in HyBro.
So the point is whether we want to completely replace them by Research notes which is their main usecase, or to add a Research notes field while keeping a more explicit Free Tags section with autocompletion. The main usecase I can imagine for autocompleted freetags woul be for boolean values which we don't want to fill for all entities but just actually "tag" some with. For instance in polarisation's future extension, having a simple tag identifying which entities are added as european candidates, or which medias are paywalled, without having to set it to false to all others.

**Comment by jacomyma** [comment]
Great! So my rationale is the following. The point of having tags is datafication, but free tags are a poor way to enrich the corpus anyway. As a consequence I would as well stick to an actual usage, ie. text notes, and completely remove the datafication aspect (autocomplete). Non datafied free tags is just text notes: users can still write a list of expressions as their note if they want.

**Comment by paulgirard** [comment]
+1

**Comment by boogheta** [comment]
All right, sounds like the description of the issue can remain as such then, nothing more to do than rename, reformat and remove autocompletion. So the issue's now ready @mydu :)
