### ISSUE TITLE
Disable adding tags on Discovered entities

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#62]
"Categories" and "Annotations" menus should be greyes/disabled in the sidebar when visiting a WebEntity with the status "Discovered". Hovering the zones should display a tooltip saying something like "Please set the status of this WebEntity before categorising it"

Warning : they should of course reappear if the user changes the status from the sidebar

**Comment by robindemourat** [comment]
I would advise to grey/disable interactions on them rather than not displaying them at all, as a first step (to avoid inconsistencies for users)

**Comment by boogheta** [comment]
fine also with me, maybe add then a tooltip on hovering these blocks 
I'm updating the description
