### ISSUE TITLE
Impossible to create a corpus with an accent in the password

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#68]
How to reproduce :

1. go to a server and create a new corpus
1. use "médialab" as password

The corpus is never created and hybro is frozen in the corpus creation loading state

**Comment by boogheta** [comment]
My first instinct led me to believe this was rather a Hyphe API issue than HyBro's but actually on the regular hyphe front, passwords with accents such as médialab do work properly, so I guess this is in HyBro's API calls there is some bad encoding gestion. What surprises me is I don't remember having the same issue with tags whereas it should probably behave the same

**Comment by boogheta** [comment]
Well I just tried and didn't encounter the issue, so I invite mr @robindemourat to retry on his side :)

**Comment by robindemourat** [comment]
indeed, I retried and it worked. Probably the cause was not that. My bad ! closing.
