### ISSUE TITLE
Enable cmd + f in pages

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#69]
It would be useful to be able to use the search function of the browser in browsing sections (user test card 138).

Possible hint : use [`window.find()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/find) ?

Possible doc : https://discuss.atom.io/t/using-webcontents-findinpage-to-implement-typical-find-function/25309/9

**Comment by boogheta** [comment]
probably useful for this: https://github.com/electron/electron/blob/v2.0.18/docs/api/web-contents.md#event-found-in-page

**Comment by mydu** [comment]
if open multiple tabs and then call `webview.findInPage()` on certain webview will crash the electron app
