### ISSUE TITLE
[Redesign] UrlBar

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#75]
mockup's "Brower bar" stories

- [x] integrate mockup
- [x] plug cover/homepage setting button (+ different display when presently on the homepage)
- [x] remove prefixSetting feature ("+" button) 
- [x] for IN entities, display a new + button to be plugged later with IN modal (cf "reviewing an IN" story #85)

## Related stories in the storybook

`Browser bar`

For a prospection entity

<img width="1055" alt="Capture d’écran 2019-06-18 à 09 58 35" src="https://user-images.githubusercontent.com/1876890/59663697-e0e63b80-91af-11e9-8028-fcc73dbec169.png">

For an IN entity

<img width="1055" alt="Capture d’écran 2019-06-18 à 09 58 44" src="https://user-images.githubusercontent.com/1876890/59663677-d62ba680-91af-11e9-86cd-c5af4ad39cac.png">

When the browsed page is the homepage of the entity (homepage button is active > it should not be clickable)

<img width="1057" alt="Capture d’écran 2019-06-18 à 09 58 55" src="https://user-images.githubusercontent.com/1876890/59663669-d3c94c80-91af-11e9-99e3-7899d3176ea8.png">

**Comment by robindemourat** [comment]
- [ ] browser bar styling issues for new tab content
- [ ] URL bar -> display prefix like in the previous version (cf storybook)
- [ ] browser bar -> display "previous" and "next" buttons when they are disabled, but with opacity 0.5
- [ ] when creating a new tab, app should focus on the URL bar

**Comment by boogheta** [comment]
closing this one and reintroducing the single part remaining
