### ISSUE TITLE
[Redesign] Integrate "Browsed WebEntity" sidebar

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#76]
- Header with:
  + [x] Entity name not editable but clickable when not in the homepage (loads the homepage if clicked)
  + [x] next/previous entity buttons (disabled when relevant) 
- [x] "WebEntity status" cartel (cartel not foldable when status DISCOVERED)
- [x] "WebEntity name" edition input (cartel not foldable when status DISCOVERED)
- [x] Handle in state the open/closed statuses of all cartels

## Related stories in the storybook

`Global layout proposal`

Notes on editing the mockups as starting points :

The `EditionCartel` is generic and is used as a base container for this view components.

The header is not separated as a pure component but probably should be separated.

<img width="414" alt="Capture d’écran 2019-06-18 à 11 39 25" src="https://user-images.githubusercontent.com/1876890/59671321-bf8c4c00-91bd-11e9-961f-52496a55adf6.png">

**Comment by robindemourat** [comment]
- [ ] link to homepage creates a bug
- [ ] in aside column, top left mode switch styling issue (probably linked to the tabs container styling)
