### ISSUE TITLE
[Redesign] "Known webpages" cartel

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#77]
- [x] To embed inside a foldable cartel within the "Browsed webentity" sidebar
- [x] Reintegrate in new component the CSS for displaying only the end of the pages url with ellipsis at the beginning
- [x] Plug homepage button
- [x] Plug "Download list" button 
- [x] Add the blue background to the currently displayed page

## Related stories in the storybook

`Known webpages`

The mockup does not integrate the feature of "displaying only the end of the pages url with ellipsis at the beginning".

<img width="522" alt="Capture d’écran 2019-06-18 à 11 41 10" src="https://user-images.githubusercontent.com/1876890/59671471-fd897000-91bd-11e9-85c6-1e7a4e2c3925.png">

**Comment by robindemourat** [comment]
- [ ] known pages -> when the active page is the homepage, the button should have a blue background and white border (for consistency reasons)
