### ISSUE TITLE
[Redesign] "Linked webentities" cartel

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#79]
- [x] Integrate CardsList and EntityCard components
- [x] Plug "cited by N entities" to webentity.indegree
- [x] Plug "download list" button
- [x] Plug navigation (clicking on all card except buttons opens webentity in a new tab in the background)
- [x] Plug actions to ram list of actions
- [x] Plug discard/apply buttons to API calls for all actions (max 2 calls : store.set_webentities_status + store.merge_webentities_into_another) 

## Related stories in the storybook

`Linked webentities`

Default state :

<img width="520" alt="Capture d’écran 2019-06-18 à 11 42 31" src="https://user-images.githubusercontent.com/1876890/59671571-36c1e000-91be-11e9-8578-bef4bbc6b6b4.png">

State with actions pending :

<img width="522" alt="Capture d’écran 2019-06-18 à 11 42 39" src="https://user-images.githubusercontent.com/1876890/59671569-36294980-91be-11e9-9815-bd3c93f996f1.png">

**Comment by robindemourat** [comment]
- [ ] linked webentities -> it should not be possible to tick both "UND."/"OUT" action and "MERGE"
- [ ] linked webentities -> change wording of confirm button (remove "on webentities") for layout reasons
