### ISSUE TITLE
[Redesign] "Tags" cartel

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#80]
- [x] Integrate the mockup inside the existing component

## Related stories in the storybook

`Tags cartel`

Empty :

<img width="520" alt="Capture d’écran 2019-06-18 à 11 44 34" src="https://user-images.githubusercontent.com/1876890/59671771-89030100-91be-11e9-9621-67bdc05595b1.png">

With values :

<img width="517" alt="Capture d’écran 2019-06-18 à 11 44 40" src="https://user-images.githubusercontent.com/1876890/59671768-886a6a80-91be-11e9-8fde-20838a87aad7.png">

When choosing a value in existing ones :

<img width="516" alt="Capture d’écran 2019-06-18 à 11 44 48" src="https://user-images.githubusercontent.com/1876890/59671767-886a6a80-91be-11e9-8d97-d6cc6e944f58.png">

When inputting a new value :

<img width="520" alt="Capture d’écran 2019-06-18 à 11 44 58" src="https://user-images.githubusercontent.com/1876890/59671766-886a6a80-91be-11e9-8da7-0e43dad2eb1b.png">

**Comment by robindemourat** [comment]
- [ ] tags -> when creating a new category, it should focus on the newly created input
- [ ] tags -> when adding a new value for a tag, it should display it right away and not wait for server response
- [ ] tags creatable -> when editing an existing tag, its text should be editable
- [ ] tags creatable -> when existing, display a cross/remove button
