### ISSUE TITLE
[Redesign] "Field notes" cartel

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#81]
- [x] Plug new component with API call
- [x] Plug edit note button with double API call (remove existing + add new)

## Related stories in the storybook

`Field notes`

Default :

<img width="520" alt="Capture d’écran 2019-06-18 à 11 47 23" src="https://user-images.githubusercontent.com/1876890/59671997-f31ba600-91be-11e9-8fc4-b4880e29e01e.png">

With notes:

<img width="520" alt="Capture d’écran 2019-06-18 à 11 47 43" src="https://user-images.githubusercontent.com/1876890/59671996-f31ba600-91be-11e9-83ff-080d12dc6606.png">

When "editing" an existing note:

<img width="519" alt="Capture d’écran 2019-06-18 à 11 49 54" src="https://user-images.githubusercontent.com/1876890/59672135-39710500-91bf-11e9-94f7-a5219759aeff.png">

**Comment by robindemourat** [comment]
Little things to solve:

- [ ] field notes -> cmd + enter should allow to validate note creation/edition (low priority)
- [ ] field notes -> notes ordering bug
- [ ] field notes -> bug when updating (taking the text of the other)
- [ ] field notes -> when editing a note, cannot cancel if the textarea is empty
