### ISSUE TITLE
[redesign] Mock special case of adding to IN an entity already in IN or OUT

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#84]
When opening the IN modal, it could happen that the prefix which has been set corresponds to an existing WE in IN or OUT list.

In this case, we need to mock an additional modal leaving two choices :

* navigate to existing WE
* cancel everything and close the IN modal

**Comment by robindemourat** [comment]
Integrated but I wonder if it would not be better to check this directly in the IN modal -> when clicking on "confirm" at step 1 ("define entity URL scope"), do an API check looking for an existing IN or OUT entity with the same prefix.

**Comment by boogheta** [comment]
That's easy to do thanks to API route `store.get_lru_definedprefixes`
