### ISSUE TITLE
[Redesign] "Inquiry overview" tab in sidebar

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#86]
- [x] Integrate "Current webentities list" cartel (plug total numbers, when clicking on a different list, call API to refresh list below, 100 by 100)
- [ ] Implement search feature using store.search_webentities with input keywords in allFieldsKeywords, and status of the current list as fieldKeywords  (ask @boogheta for help :) )
- [x] validate fast action buttons working with validation
- [x] clicking on a webentity opens it in the current tab (warning: different behaviour than LinkedWebentities) and switches the sidebar to the "Browsed webentity" tab 
- [ ] If fast actions are pending, and user switches to the "Browsed webentity" tab (either by clicking on it, or clicking on a webentity in the list), a new modal opens (to be designed) with three options : cancel, discard actions and proceed, validate actions and proceed.
- [x] Implement filters [To be discussed]
- [ ] bonus feature : virtualize list of entities (but not really necessary)

## Related stories in the storybook

`Global layout proposal`

Default:

<img width="1275" alt="Capture d’écran 2019-06-18 à 11 56 10" src="https://user-images.githubusercontent.com/1876890/59672612-185ce400-91c0-11e9-9203-9eb2824944c6.png">

With pending actions:

<img width="1277" alt="Capture d’écran 2019-06-18 à 11 55 58" src="https://user-images.githubusercontent.com/1876890/59672615-18f57a80-91c0-11e9-87e6-92dc610aef5e.png">

When leaving with pending actions:

<img width="1277" alt="Capture d’écran 2019-06-18 à 11 55 43" src="https://user-images.githubusercontent.com/1876890/59672616-18f57a80-91c0-11e9-883d-801f23d725cb.png">

**Comment by mydu** [comment]
Questions:

- [ ] if api for fetch no-tag and incomplete-tag webentities exist?
- [ ] click webentity card would open new tab or set current tab?
- [ ] search filter will request a `wordsearch` api or just do local search?

**Comment by boogheta** [comment]
Answers:
- cf https://github.com/medialab/hyphe-browser/issues/102
- for now use the current tab, but may change later function of results of experimenting with current behavior and branch in https://github.com/medialab/hyphe-browser/issues/101
- there is no combination of wordsearch, status filter and mistaggeg in the API for now, so local filtering will do for now (although it will result in a strange behavior for Prospect since its results are paginated)

**Comment by mydu** [comment]
Updating selected stack pattern
- [ ] fetch webentities when select 
- [ ] fetch webentities  when 'change status' action submitted
- [ ] fetch mistagged webentities  when filter updated
- [ ] fetch(select if already exist) stack when switch tabs **(or not - To be discussed)**
- [ ] fetch when `status.corpus.traph.webentities` !== `total_results` from last fetch
- [ ] ISSUE - pagination on 'DISCOVERED' list will not be preserved
