### ISSUE TITLE
Merge multiple entities from fast actions in Citing/Cited entities within a modal

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#89]
A lot of merge actions from the "linked entities" cartel may consist in merging social network pages into the browsed webentity. But for instance for twitter the default prefix is set at the root of the social network. So if I "merge" a "twitter" entity I might accidentally include all the twitter pages, while I just want to merge the page(s) related to my entity.

I see two possible approach for this error prevention problem:

1. decide that this has to be solved at the level of default prefix definition
1.  when merging "prospection" entities, display a modal asking to confirm the prefix level of the pages to merge within the current one

Remember to redisplay the + button when this is fixed

So after discussions, this can be handled by doing so:
- [x] reenable the buttons within the cited/citing webentities lists

when clicking "validate" if there are merge actions to process, then:
- [x] first run the other actions (status changes)
- [x] then open a modal with a list of blocks for each merge action
- [x] each merge action contains a cancel button
- [x] each merge action contains a slider to decide which part of the other entity to merge within the current one
- [x] adjust texts FR/EN
- [ ] improve design for more readability, cf #192
- [x] when we click all "Cancel merge" buttons in a mergeactions modal, the modal should automatically close itself without having to click the global "Cancel" button at the bottom

**Comment by boogheta** [comment]
- [ ] reenable the buttons within the cited/citing webentites lists
if there are merge actions, 
- [ ] first run the other actions (status changes)
- [ ] then open a modal with a list of blocks for each merge action
- [ ] each merge action contains a cancel button
- [ ] each merge action contains a slider to decide which part of the other entity to merge within the current one

**Comment by boogheta** [comment]
Everything seems good, I just need to adjust the wording for both languages, and this raises the need to fix #165 on one part, and another design issue with the names of the linked entities being cut too much making it hard to know whether you're deadling with Twitter or just a part of it for instance, I'll open another issue for this

**Comment by boogheta** [comment]
Extra suggestion here : when we click all "Cancel merge" buttons in a mergeactions modal, the modal should automatically close itself without having to click the global "Cancel" button at the bottom

**Comment by boogheta** [comment]
there is still the redesign to finish, but it has its own dedicated issue, so i'm closing this one here
