### ISSUE TITLE
When a Prospection entity redirects elsewhere, the merge popup wants to merge entity into itself

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#91]
To replicate, use for instance the demo server and the corpus "maison" (password: "test"):
- select the IN stack
- click the stack to select the "Stream-French.co" entity
=> it redirects the tab to "french-stream.cc" and opens the Merge popup, which is good, BUT it proposes to merge "Stream-French.co" into "Stream-French.co" instead of into "french-stream.cc", and if we click "Merge" it logically fails as we are trying to merge an entity into itself and not into another.

**Comment by mydu** [comment]
introduce by the fix https://github.com/medialab/hyphe-browser/commit/6adb18113914e602e296ffaf78789634e31bb72c
