### ISSUE TITLE
[Redesign] in webentities lists, find a design solution for displaying whether an entity has already been visited

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#94]
Bold text ? check icon ? color change ?

**Comment by robindemourat** [comment]
Done in storybook, todo in main code

**Comment by robindemourat** [comment]
Implemented in main code.

@boogheta it is now implemented in the cards design, works fine for the stacks list ("inquiry overview") but not in the `Linked webentities cartel` because the `viewed` property is not populated in the data of linked webentities. I did not investigate but suppose it would need some changes upstream to include the `viewed` prop in the response of the API call for linked webentities.

**Comment by boogheta** [comment]
The thing is this is not a property which Hyphe's server "knows" about, this is only an internal attribute within Hyphe Browser.
We could decide to add some kind of internal tag "visited: true" maybe, but that raises different questions on a larger scale.
Another simplier option would be to keep this internal and use the browser's navigation history to populate this info.

**Comment by robindemourat** [comment]
Ok, first version implemented using existing method for this: in the list of webentities (in `inquiry overview`) the feature was already implemented thanks to an information added to the redux state when triggering the action `VIEW_WEBENTITY` ([here](https://github.com/medialab/hyphe-browser/blob/11aca66bf5e3338af67bba3f06a56fb851bd0619/app/reducers/stacks.js#L96)) during user navigation.

I implemented the `viewed` feature in the linked entities using the same method, but the problem with this method is that it does not persist accross sessions (closing and opening the app will reset it).

We could indeed rely on the browser or localStorage data, but I guess this should be discussed and opened as a new issue !

**Comment by boogheta** [comment]
yep sounds fair, so I guess we can close this one for now.
Also imho, it's quite rare that one would visit a discovered entity and not change its status, so I don't think it's toot critical that this does not persist across sessions, this is overall a need to know in the currently loaded entity stack which entities have already been processed or not in the case these lists are not refreshed on the fly
