### ISSUE TITLE
Things to fix from sprint 1 review

### ISSUE THREAD

**Issue by robindemourat** [medialab/hyphe-browser#98]
- [x] cannot close antepenultimate tab with cmd+w
- [x] switch color of prospects status to DISCOVERED's color
- [x] put prospect status as uppercase
- [x] background color of tabs is the same as tabs
- [x] when switching tabs, new tab content load in a very small screen before taking a correct shape (add something like `min-width:100%;min-height:100%` to the content)
- [x] left column header switch buttons tooltips display below browser tabs
- [x] header -> corpus close btn -> display hint in bottom instead of left
- [ ] hyphe tab issues (from TabBrowser/WebView : https://github.com/medialab/hyphe-browser/blob/master/app/containers/BrowserTabs/WebView.js#L114-L122 ):
    - [ ] it should not reload when switching, except if it is in the network view
    - [x] whenever the hyphe page is loaded, the top left "corpus name" + "close corpus button" from the top-left corner
    - [x] (benjamin) check electron's user agent changed for hyphe frontend behaviour with opening links in new tabs
    - [ ] whenever a new tab is opened by a link to hyphe, it should not open it in the browser view but remain in the hyphe view (low priority) (was handled previously here: https://github.com/medialab/hyphe-browser/blob/master/app/containers/BrowserTabs/BrowserTabContent.js#L105-L108 )
- [x] (Robin) style the search engine in new tab content
- [x] when opening multiple tabs, the left column gets reduced -> add a min-width to the left column and overflow-x to the tabs container
- [x] new tab content : when entering an URL without protocol, add a protocol automatically
- [x] add a + inside the "new tab" button
- [x] when switching from a webview tab to a new tab content then switching back, the aside column mode should be remembered (if I was in "browsed webentity" mode I want to be back on it)
- [x] ctrl + R should always refresh the webview and shift + ctrl + R should refresh the app in dev and hard refresh the webview in production
- [x] when opening a link in a new tab from a click (from within the webview or from the sidebar), open the new tab next to current one instead of opening it at the end of the tabs list] 
- [x] (benjamin) add in Hyphe backend a route to edit a tag

**Comment by mydu** [comment]
some css messed up because of the css package in [vendo](https://github.com/medialab/hyphe-browser/tree/master/vendors/)r folder on top https://github.com/medialab/hyphe-browser/blob/master/app/index-dev.html#L7

**Comment by boogheta** [comment]
I'm closing this one and reopening dedicated issues for the remaining issues
