### ISSUE TITLE
Temporary simplified stacks handling

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#99]
- [x] turn corpus indicators into stack buttons (like before : clicking on IN, UND, PROSPECT, OUT fills the stack with the result of the corresponding api call)
- [x] turn the TAG button in the new tab page into filling the stack with the previous "IN Untagged" list
- [x] In the browsed webentity, plug the next and previous buttons to select the next/previous entity in the stack

**Comment by mydu** [comment]
design/implementation issues:
- [ ] when open a new webentity(e.g. "DISCOVERED") which status is not same as current selected stack("IN"), will auto set selected stack according to the actived webentitiy
- [ ] next/prev navigation might fail to track index if entity is not found in stack list(cause the DISCOVERED stack is set to `limit=200`)
- [ ] 'IN Untagged" entities has a status with 'IN', with the previous implementation this list could not be preserved in status -> could not navigate using next/prev

**Comment by mydu** [comment]
disable select stack on corpus indicator https://github.com/medialab/hyphe-browser/commit/99e2366e083cb13f7b993ebba41799d30c7f902e
